/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EducationRouteImport } from './routes/education'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetugasStatusRouteImport } from './routes/petugas.status'
import { Route as PetugasRequestRouteImport } from './routes/petugas.request'
import { Route as PetugasProfileRouteImport } from './routes/petugas.profile'
import { Route as PetugasJadwalHariIniRouteImport } from './routes/petugas.jadwal-hari-ini'
import { Route as PetugasHistoryRouteImport } from './routes/petugas.history'
import { Route as PetugasDashboardRouteImport } from './routes/petugas.dashboard'
import { Route as AppStatusRouteImport } from './routes/app.status'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppRequestRouteImport } from './routes/app.request'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPetugasRouteImport } from './routes/admin.petugas'
import { Route as AdminEducationRouteImport } from './routes/admin.education'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasStatusRoute = PetugasStatusRouteImport.update({
  id: '/petugas/status',
  path: '/petugas/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasRequestRoute = PetugasRequestRouteImport.update({
  id: '/petugas/request',
  path: '/petugas/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasProfileRoute = PetugasProfileRouteImport.update({
  id: '/petugas/profile',
  path: '/petugas/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasJadwalHariIniRoute = PetugasJadwalHariIniRouteImport.update({
  id: '/petugas/jadwal-hari-ini',
  path: '/petugas/jadwal-hari-ini',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasHistoryRoute = PetugasHistoryRouteImport.update({
  id: '/petugas/history',
  path: '/petugas/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasDashboardRoute = PetugasDashboardRouteImport.update({
  id: '/petugas/dashboard',
  path: '/petugas/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/app/status',
  path: '/app/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/app/schedule',
  path: '/app/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestRoute = AppRequestRouteImport.update({
  id: '/app/request',
  path: '/app/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPetugasRoute = AdminPetugasRouteImport.update({
  id: '/admin/petugas',
  path: '/admin/petugas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEducationRoute = AdminEducationRouteImport.update({
  id: '/admin/education',
  path: '/admin/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/petugas': typeof AdminPetugasRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request': typeof AppRequestRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/status': typeof AppStatusRoute
  '/petugas/dashboard': typeof PetugasDashboardRoute
  '/petugas/history': typeof PetugasHistoryRoute
  '/petugas/jadwal-hari-ini': typeof PetugasJadwalHariIniRoute
  '/petugas/profile': typeof PetugasProfileRoute
  '/petugas/request': typeof PetugasRequestRoute
  '/petugas/status': typeof PetugasStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/petugas': typeof AdminPetugasRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request': typeof AppRequestRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/status': typeof AppStatusRoute
  '/petugas/dashboard': typeof PetugasDashboardRoute
  '/petugas/history': typeof PetugasHistoryRoute
  '/petugas/jadwal-hari-ini': typeof PetugasJadwalHariIniRoute
  '/petugas/profile': typeof PetugasProfileRoute
  '/petugas/request': typeof PetugasRequestRoute
  '/petugas/status': typeof PetugasStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/education': typeof EducationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/education': typeof AdminEducationRoute
  '/admin/petugas': typeof AdminPetugasRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/request': typeof AppRequestRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/status': typeof AppStatusRoute
  '/petugas/dashboard': typeof PetugasDashboardRoute
  '/petugas/history': typeof PetugasHistoryRoute
  '/petugas/jadwal-hari-ini': typeof PetugasJadwalHariIniRoute
  '/petugas/profile': typeof PetugasProfileRoute
  '/petugas/request': typeof PetugasRequestRoute
  '/petugas/status': typeof PetugasStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/education'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/education'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/requests'
    | '/admin/schedules'
    | '/admin/users'
    | '/app/dashboard'
    | '/app/history'
    | '/app/profile'
    | '/app/request'
    | '/app/schedule'
    | '/app/status'
    | '/petugas/dashboard'
    | '/petugas/history'
    | '/petugas/jadwal-hari-ini'
    | '/petugas/profile'
    | '/petugas/request'
    | '/petugas/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/education'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/education'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/requests'
    | '/admin/schedules'
    | '/admin/users'
    | '/app/dashboard'
    | '/app/history'
    | '/app/profile'
    | '/app/request'
    | '/app/schedule'
    | '/app/status'
    | '/petugas/dashboard'
    | '/petugas/history'
    | '/petugas/jadwal-hari-ini'
    | '/petugas/profile'
    | '/petugas/request'
    | '/petugas/status'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/education'
    | '/login'
    | '/register'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/education'
    | '/admin/petugas'
    | '/admin/profile'
    | '/admin/requests'
    | '/admin/schedules'
    | '/admin/users'
    | '/app/dashboard'
    | '/app/history'
    | '/app/profile'
    | '/app/request'
    | '/app/schedule'
    | '/app/status'
    | '/petugas/dashboard'
    | '/petugas/history'
    | '/petugas/jadwal-hari-ini'
    | '/petugas/profile'
    | '/petugas/request'
    | '/petugas/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  EducationRoute: typeof EducationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEducationRoute: typeof AdminEducationRoute
  AdminPetugasRoute: typeof AdminPetugasRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRequestRoute: typeof AppRequestRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppStatusRoute: typeof AppStatusRoute
  PetugasDashboardRoute: typeof PetugasDashboardRoute
  PetugasHistoryRoute: typeof PetugasHistoryRoute
  PetugasJadwalHariIniRoute: typeof PetugasJadwalHariIniRoute
  PetugasProfileRoute: typeof PetugasProfileRoute
  PetugasRequestRoute: typeof PetugasRequestRoute
  PetugasStatusRoute: typeof PetugasStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/status': {
      id: '/petugas/status'
      path: '/petugas/status'
      fullPath: '/petugas/status'
      preLoaderRoute: typeof PetugasStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/request': {
      id: '/petugas/request'
      path: '/petugas/request'
      fullPath: '/petugas/request'
      preLoaderRoute: typeof PetugasRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/profile': {
      id: '/petugas/profile'
      path: '/petugas/profile'
      fullPath: '/petugas/profile'
      preLoaderRoute: typeof PetugasProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/jadwal-hari-ini': {
      id: '/petugas/jadwal-hari-ini'
      path: '/petugas/jadwal-hari-ini'
      fullPath: '/petugas/jadwal-hari-ini'
      preLoaderRoute: typeof PetugasJadwalHariIniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/history': {
      id: '/petugas/history'
      path: '/petugas/history'
      fullPath: '/petugas/history'
      preLoaderRoute: typeof PetugasHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/dashboard': {
      id: '/petugas/dashboard'
      path: '/petugas/dashboard'
      fullPath: '/petugas/dashboard'
      preLoaderRoute: typeof PetugasDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/status': {
      id: '/app/status'
      path: '/app/status'
      fullPath: '/app/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/app/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/request': {
      id: '/app/request'
      path: '/app/request'
      fullPath: '/app/request'
      preLoaderRoute: typeof AppRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/petugas': {
      id: '/admin/petugas'
      path: '/admin/petugas'
      fullPath: '/admin/petugas'
      preLoaderRoute: typeof AdminPetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/education': {
      id: '/admin/education'
      path: '/admin/education'
      fullPath: '/admin/education'
      preLoaderRoute: typeof AdminEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  EducationRoute: EducationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEducationRoute: AdminEducationRoute,
  AdminPetugasRoute: AdminPetugasRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppRequestRoute: AppRequestRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppStatusRoute: AppStatusRoute,
  PetugasDashboardRoute: PetugasDashboardRoute,
  PetugasHistoryRoute: PetugasHistoryRoute,
  PetugasJadwalHariIniRoute: PetugasJadwalHariIniRoute,
  PetugasProfileRoute: PetugasProfileRoute,
  PetugasRequestRoute: PetugasRequestRoute,
  PetugasStatusRoute: PetugasStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
